/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReadmeStudioRouteImport } from './routes/readme-studio'
import { Route as ApiReadmeDraftRouteImport } from './routes/api/readme-draft'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadmeStudioRoute = ReadmeStudioRouteImport.update({
  id: '/readme-studio',
  path: '/readme-studio',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReadmeDraftRoute = ApiReadmeDraftRouteImport.update({
  id: '/api/readme-draft',
  path: '/api/readme-draft',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/readme-studio': typeof ReadmeStudioRoute
  '/api/readme-draft': typeof ApiReadmeDraftRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/readme-studio': typeof ReadmeStudioRoute
  '/api/readme-draft': typeof ApiReadmeDraftRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/readme-studio': typeof ReadmeStudioRoute
  '/api/readme-draft': typeof ApiReadmeDraftRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/readme-studio' | '/api/readme-draft'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/readme-studio' | '/api/readme-draft'
  id: '__root__' | '/' | '/readme-studio' | '/api/readme-draft'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ReadmeStudioRoute: typeof ReadmeStudioRoute
  ApiReadmeDraftRoute: typeof ApiReadmeDraftRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/readme-studio': {
      id: '/readme-studio'
      path: '/readme-studio'
      fullPath: '/readme-studio'
      preLoaderRoute: typeof ReadmeStudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/readme-draft': {
      id: '/api/readme-draft'
      path: '/api/readme-draft'
      fullPath: '/api/readme-draft'
      preLoaderRoute: typeof ApiReadmeDraftRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ReadmeStudioRoute: ReadmeStudioRoute,
  ApiReadmeDraftRoute: ApiReadmeDraftRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
